### ISSUE TITLE
Can you put single .js on bower rather than whole project?

### ISSUE THREAD

**Issue by akhopkar** [iamisti/md-data-table#6]
Hi there,

I saw your demo and since I'm going with angular-material I would like to use your data table.

I cloned your repository and after npm install and bower install, did a gulp on the main directory.  Most tasks except the test and run server tasks seemed to work.  However, I don't see anything like a dist folder with a file like md-data-table.js that I can include in my project.  I saw the same project when I tried to do bower install md-data-table.

I was wondering if it would be possible for you to put this project on bower in such a way that rather than the user pulling the entire project with dependencies, it would be extremely helpful if after a bower-install I could just include 1 .js file and 1 .css file into my project in order to use your module.

FYI

I got this output when I ran gulp

[19:04:57] Using gulpfile ~/Dev/third_party_modules/md-data-table/gulpfile.js
[19:04:57] Starting 'default'...
[19:04:57] Starting 'start development webserver'...
[19:04:57] Finished 'start development webserver' after 6.41 ms
[19:04:57] Starting 'build'...
[19:04:57] Starting 'test'...
[19:04:57] Starting 'unit'...
[19:04:57] Server started http://localhost:9000
[19:04:57] LiveReload started on port 35729
[19:04:57] Starting Karma server...

/home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:jasmine-jquery"! (Resolving: framework:jasmine-jquery)
  at error (/home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/node_modules/di/lib/injector.js:22:68)
  at Object.parent.get (/home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/node_modules/di/lib/injector.js:9:13)
  at [object Object].get (/home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/node_modules/di/lib/injector.js:54:19)
  at /home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/lib/server.js:321:14
  at Array.forEach (native)
  at Object.exports.start (/home/amarish/Dev/third_party_modules/md-data-table/node_modules/karma/lib/server.js:320:21)
  at Object.<anonymous> (/home/amarish/Dev/third_party_modules/md-data-table/node_modules/gulp-karma/lib/background.js:3:8)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

[19:04:58] 'unit' errored after 957 ms
[19:04:58] Error in plugin 'gulp-karma'

**Comment by iamisti** [comment]
Thanks for your comment.
I'm still working on the project and it does not have a fully prepared repository.
The table does not support any functionality at the moment, but if you need to use only because of the UI is based on angular material, then I can do it for you.

**Comment by iamisti** [comment]
@akhopkar it's fixed.
Now u can use this table. At the moment the material design is implemented, but the functionalities are missing at the moment.
But still it's more than nothing. Later on it will have more and more features. (my plan is to have a new feature in every week)
